--
-- PostgreSQL database dump
--

\restrict ROZrYF6s3jYu6dhjnDfArXG4w7chY75KbQZeItLQapF7s1ITwwGc0YhEz5ykLwS

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: sp_registrar_seguimiento_terreno(integer, date, time without time zone, text[], integer); Type: PROCEDURE; Schema: public; Owner: postgres
--

CREATE PROCEDURE public.sp_registrar_seguimiento_terreno(IN p_id_seguimiento integer, IN p_fecha date, IN p_hora time without time zone, IN p_actividades text[], IN p_usuario_creador integer)
    LANGUAGE plpgsql
    AS $$
BEGIN
    INSERT INTO tabla_seguimiento_principal (
        id_seguimiento, 
        fecha, 
        hora
    ) VALUES (
        p_id_seguimiento, 
        p_fecha, 
        p_hora
    );

    
    INSERT INTO tabla_actividades_terreno (
        id_seguimiento,
        fecha,
        hora,
        actividades_cargadas,
        usuario_creador
    ) VALUES (
        p_id_seguimiento,
        p_fecha,
        p_hora,
        array_to_string(p_actividades, ', '),
        p_usuario_creador
    );

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Error al registrar el seguimiento en terreno: %', SQLERRM;
END;
$$;


ALTER PROCEDURE public.sp_registrar_seguimiento_terreno(IN p_id_seguimiento integer, IN p_fecha date, IN p_hora time without time zone, IN p_actividades text[], IN p_usuario_creador integer) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actividad_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad_terreno (
    id_actividad_terreno smallint NOT NULL,
    nombre character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.actividad_terreno OWNER TO postgres;

--
-- Name: actividad_terreno_id_actividad_terreno_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad_terreno ALTER COLUMN id_actividad_terreno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_terreno_id_actividad_terreno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actividad_zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad_zoocriadero (
    id_actividad_zoocriadero smallint NOT NULL,
    nombre character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.actividad_zoocriadero OWNER TO postgres;

--
-- Name: actividad_zoocriadero_id_actividad_zoocriadero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad_zoocriadero ALTER COLUMN id_actividad_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_zoocriadero_id_actividad_zoocriadero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barrio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barrio (
    id_barrio smallint NOT NULL,
    nombre character varying(120) NOT NULL,
    id_comuna smallint NOT NULL
);


ALTER TABLE public.barrio OWNER TO postgres;

--
-- Name: comuna; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comuna (
    id_comuna smallint NOT NULL,
    nombre character varying(120) NOT NULL
);


ALTER TABLE public.comuna OWNER TO postgres;

--
-- Name: deposito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deposito (
    id_deposito smallint NOT NULL,
    id_sitio smallint NOT NULL,
    id_tipo_deposito smallint NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.deposito OWNER TO postgres;

--
-- Name: deposito_id_deposito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deposito ALTER COLUMN id_deposito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposito_id_deposito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_codes (
    id_reset integer NOT NULL,
    id_usuario smallint NOT NULL,
    codigo_hash character varying(255) NOT NULL,
    expira_en timestamp without time zone NOT NULL,
    intentos smallint DEFAULT 0 NOT NULL,
    verificado boolean DEFAULT false NOT NULL,
    usado_en timestamp without time zone,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.password_reset_codes OWNER TO postgres;

--
-- Name: password_reset_codes_id_reset_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_codes ALTER COLUMN id_reset ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_codes_id_reset_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permiso_rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permiso_rol (
    id_permiso smallint NOT NULL,
    id_rol smallint NOT NULL,
    pagina character varying(100) NOT NULL,
    etiqueta character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.permiso_rol OWNER TO postgres;

--
-- Name: permiso_rol_id_permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permiso_rol ALTER COLUMN id_permiso ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.permiso_rol_id_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol smallint NOT NULL,
    nombre_rol character varying(50) NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: seguimiento_terreno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seguimiento_terreno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.seguimiento_terreno_id_seq OWNER TO postgres;

--
-- Name: seguimiento_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_terreno (
    id_seguimiento_terreno smallint DEFAULT nextval('public.seguimiento_terreno_id_seq'::regclass) NOT NULL,
    id_deposito smallint NOT NULL,
    id_usuario smallint NOT NULL,
    fecha date NOT NULL,
    id_actividad_terreno smallint NOT NULL,
    ph numeric(3,1),
    temperatura numeric(4,1),
    larvas_aedes smallint,
    pupas smallint,
    larvas_culex smallint
);


ALTER TABLE public.seguimiento_terreno OWNER TO postgres;

--
-- Name: seguimiento_zoo_actividad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_zoo_actividad (
    id_seguimiento_zoo smallint NOT NULL,
    id_actividad_zoocriadero smallint NOT NULL
);


ALTER TABLE public.seguimiento_zoo_actividad OWNER TO postgres;

--
-- Name: seguimiento_zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_zoocriadero (
    id_seguimiento_zoo smallint NOT NULL,
    id_tanque smallint NOT NULL,
    id_usuario smallint NOT NULL,
    fecha date NOT NULL,
    ph numeric(3,1),
    temperatura numeric(4,1),
    alevines_nacidos smallint,
    observaciones text,
    cloro numeric(4,2),
    muertos_macho smallint DEFAULT 0,
    muertos_hembra smallint DEFAULT 0
);


ALTER TABLE public.seguimiento_zoocriadero OWNER TO postgres;

--
-- Name: seguimiento_zoocriadero_id_seguimiento_zoo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seguimiento_zoocriadero ALTER COLUMN id_seguimiento_zoo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguimiento_zoocriadero_id_seguimiento_zoo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sitio_barrio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sitio_barrio (
    id_sitio_barrio smallint NOT NULL,
    id_sitio smallint NOT NULL,
    id_barrio smallint NOT NULL
);


ALTER TABLE public.sitio_barrio OWNER TO postgres;

--
-- Name: sitio_barrio_id_sitio_barrio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sitio_barrio ALTER COLUMN id_sitio_barrio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sitio_barrio_id_sitio_barrio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sitio_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sitio_terreno (
    id_sitio smallint NOT NULL,
    direccion character varying(50),
    latitud numeric(9,6),
    longitud numeric(9,6),
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.sitio_terreno OWNER TO postgres;

--
-- Name: sitio_terreno_id_sitio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sitio_terreno ALTER COLUMN id_sitio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sitio_terreno_id_sitio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tanque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tanque (
    id_tanque smallint NOT NULL,
    id_zoocriadero smallint NOT NULL,
    id_tipo_tanque smallint NOT NULL,
    estado character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tanque OWNER TO postgres;

--
-- Name: tanque_id_tanque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tanque ALTER COLUMN id_tanque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tanque_id_tanque_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_deposito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_deposito (
    id_tipo_deposito smallint NOT NULL,
    descripcion character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tipo_deposito OWNER TO postgres;

--
-- Name: tipo_deposito_id_tipo_deposito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_deposito ALTER COLUMN id_tipo_deposito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_deposito_id_tipo_deposito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_documento (
    id_tipo_documento smallint NOT NULL,
    nombre_tipo_documento character varying(120) NOT NULL
);


ALTER TABLE public.tipo_documento OWNER TO postgres;

--
-- Name: tipo_tanque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_tanque (
    id_tipo_tanque smallint NOT NULL,
    descripcion character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tipo_tanque OWNER TO postgres;

--
-- Name: tipo_tanque_id_tipo_tanque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_tanque ALTER COLUMN id_tipo_tanque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_tanque_id_tipo_tanque_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario smallint NOT NULL,
    id_rol smallint NOT NULL,
    documento character varying(50) NOT NULL,
    nombres character varying(50) NOT NULL,
    apellidos character varying(50) NOT NULL,
    id_tipo_documento integer NOT NULL,
    "contraseña" character varying(255) NOT NULL,
    correo character varying(150) NOT NULL,
    fecha_nacimiento date NOT NULL,
    telefono character varying(20) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zoocriadero (
    id_zoocriadero smallint NOT NULL,
    direccion character varying(50) NOT NULL,
    id_usuario smallint NOT NULL,
    id_barrio smallint NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.zoocriadero OWNER TO postgres;

--
-- Name: zoocriadero_id_zoocriadero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zoocriadero ALTER COLUMN id_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zoocriadero_id_zoocriadero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_codes password_reset_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT password_reset_codes_pkey PRIMARY KEY (id_reset);


--
-- Name: actividad_terreno pk_actividad_terreno; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_terreno
    ADD CONSTRAINT pk_actividad_terreno PRIMARY KEY (id_actividad_terreno);


--
-- Name: actividad_zoocriadero pk_actividad_zoocriadero; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_zoocriadero
    ADD CONSTRAINT pk_actividad_zoocriadero PRIMARY KEY (id_actividad_zoocriadero);


--
-- Name: barrio pk_barrio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barrio
    ADD CONSTRAINT pk_barrio PRIMARY KEY (id_barrio);


--
-- Name: comuna pk_comuna; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comuna
    ADD CONSTRAINT pk_comuna PRIMARY KEY (id_comuna);


--
-- Name: deposito pk_deposito; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT pk_deposito PRIMARY KEY (id_deposito);


--
-- Name: permiso_rol pk_permiso_rol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso_rol
    ADD CONSTRAINT pk_permiso_rol PRIMARY KEY (id_permiso);


--
-- Name: rol pk_rol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT pk_rol PRIMARY KEY (id_rol);


--
-- Name: seguimiento_terreno pk_seguimiento_terreno; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT pk_seguimiento_terreno PRIMARY KEY (id_seguimiento_terreno);


--
-- Name: seguimiento_zoo_actividad pk_seguimiento_zoo_actividad; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoo_actividad
    ADD CONSTRAINT pk_seguimiento_zoo_actividad PRIMARY KEY (id_seguimiento_zoo, id_actividad_zoocriadero);


--
-- Name: seguimiento_zoocriadero pk_seguimiento_zoocriadero; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT pk_seguimiento_zoocriadero PRIMARY KEY (id_seguimiento_zoo);


--
-- Name: sitio_barrio pk_sitio_barrio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_barrio
    ADD CONSTRAINT pk_sitio_barrio PRIMARY KEY (id_sitio_barrio);


--
-- Name: sitio_terreno pk_sitio_terreno; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_terreno
    ADD CONSTRAINT pk_sitio_terreno PRIMARY KEY (id_sitio);


--
-- Name: tanque pk_tanque; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT pk_tanque PRIMARY KEY (id_tanque);


--
-- Name: tipo_deposito pk_tipo_deposito; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_deposito
    ADD CONSTRAINT pk_tipo_deposito PRIMARY KEY (id_tipo_deposito);


--
-- Name: tipo_documento pk_tipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_documento
    ADD CONSTRAINT pk_tipo_documento PRIMARY KEY (id_tipo_documento);


--
-- Name: tipo_tanque pk_tipo_tanque; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_tanque
    ADD CONSTRAINT pk_tipo_tanque PRIMARY KEY (id_tipo_tanque);


--
-- Name: usuario pk_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT pk_usuario PRIMARY KEY (id_usuario);


--
-- Name: zoocriadero pk_zoocriadero; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT pk_zoocriadero PRIMARY KEY (id_zoocriadero);


--
-- Name: permiso_rol uq_permiso_rol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso_rol
    ADD CONSTRAINT uq_permiso_rol UNIQUE (id_rol, pagina);


--
-- Name: usuario uq_usuario_documento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uq_usuario_documento UNIQUE (documento);


--
-- Name: usuario usuario_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_correo_key UNIQUE (correo);


--
-- Name: idx_password_reset_expira; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_password_reset_expira ON public.password_reset_codes USING btree (expira_en);


--
-- Name: idx_password_reset_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_password_reset_usuario ON public.password_reset_codes USING btree (id_usuario);


--
-- Name: barrio fk_barrio_comuna; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barrio
    ADD CONSTRAINT fk_barrio_comuna FOREIGN KEY (id_comuna) REFERENCES public.comuna(id_comuna);


--
-- Name: deposito fk_deposito_sitio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT fk_deposito_sitio FOREIGN KEY (id_sitio) REFERENCES public.sitio_terreno(id_sitio);


--
-- Name: deposito fk_deposito_tipo_deposito; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT fk_deposito_tipo_deposito FOREIGN KEY (id_tipo_deposito) REFERENCES public.tipo_deposito(id_tipo_deposito);


--
-- Name: password_reset_codes fk_password_reset_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT fk_password_reset_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;


--
-- Name: permiso_rol fk_permiso_rol_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso_rol
    ADD CONSTRAINT fk_permiso_rol_rol FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: seguimiento_terreno fk_seguimiento_terreno_actividad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT fk_seguimiento_terreno_actividad FOREIGN KEY (id_actividad_terreno) REFERENCES public.actividad_terreno(id_actividad_terreno);


--
-- Name: seguimiento_terreno fk_seguimiento_terreno_deposito; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT fk_seguimiento_terreno_deposito FOREIGN KEY (id_deposito) REFERENCES public.deposito(id_deposito);


--
-- Name: seguimiento_terreno fk_seguimiento_terreno_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT fk_seguimiento_terreno_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- Name: seguimiento_zoocriadero fk_seguimiento_zoo_tanque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT fk_seguimiento_zoo_tanque FOREIGN KEY (id_tanque) REFERENCES public.tanque(id_tanque);


--
-- Name: seguimiento_zoocriadero fk_seguimiento_zoo_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT fk_seguimiento_zoo_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- Name: sitio_barrio fk_sitio_barrio_barrio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_barrio
    ADD CONSTRAINT fk_sitio_barrio_barrio FOREIGN KEY (id_barrio) REFERENCES public.barrio(id_barrio);


--
-- Name: sitio_barrio fk_sitio_barrio_sitio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_barrio
    ADD CONSTRAINT fk_sitio_barrio_sitio FOREIGN KEY (id_sitio) REFERENCES public.sitio_terreno(id_sitio);


--
-- Name: seguimiento_zoo_actividad fk_szact_actividad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoo_actividad
    ADD CONSTRAINT fk_szact_actividad FOREIGN KEY (id_actividad_zoocriadero) REFERENCES public.actividad_zoocriadero(id_actividad_zoocriadero);


--
-- Name: seguimiento_zoo_actividad fk_szact_seguimiento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoo_actividad
    ADD CONSTRAINT fk_szact_seguimiento FOREIGN KEY (id_seguimiento_zoo) REFERENCES public.seguimiento_zoocriadero(id_seguimiento_zoo);


--
-- Name: tanque fk_tanque_tipo_tanque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT fk_tanque_tipo_tanque FOREIGN KEY (id_tipo_tanque) REFERENCES public.tipo_tanque(id_tipo_tanque);


--
-- Name: tanque fk_tanque_zoocriadero; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT fk_tanque_zoocriadero FOREIGN KEY (id_zoocriadero) REFERENCES public.zoocriadero(id_zoocriadero);


--
-- Name: usuario fk_usuario_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: usuario fk_usuario_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fk_usuario_tipo_documento FOREIGN KEY (id_tipo_documento) REFERENCES public.tipo_documento(id_tipo_documento);


--
-- Name: zoocriadero fk_zoocriadero_barrio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT fk_zoocriadero_barrio FOREIGN KEY (id_barrio) REFERENCES public.barrio(id_barrio);


--
-- Name: zoocriadero fk_zoocriadero_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT fk_zoocriadero_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- PostgreSQL database dump complete
--

\unrestrict ROZrYF6s3jYu6dhjnDfArXG4w7chY75KbQZeItLQapF7s1ITwwGc0YhEz5ykLwS

