<?php
session_start();
if (empty($_SESSION['recuperacion_reset_id']) || empty($_SESSION['recuperacion_usuario_id'])) {
    header('Location: recuperar_contrasena.php');
    exit;
}
$error = $_SESSION['recuperacion_error_nueva'] ?? null;
$exito = $_SESSION['recuperacion_exito_codigo'] ?? null;
unset($_SESSION['recuperacion_error_nueva'], $_SESSION['recuperacion_exito_codigo']);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GEMO | Nueva contraseña</title><link rel="stylesheet" href="assets/css/bootstrap.min.css"><link rel="stylesheet" href="assets/css/fonts.min.css"><link rel="stylesheet" href="assets/css/gemo.css"></head><body class="gemo-login"><div class="login-wrap"><div class="login-card"><div class="gemo-login-institucional"><img src="assets/img/branding/alcaldia-escudo.png" alt="Alcaldía de Santiago de Cali"><div class="gemo-login-institucional-texto"><strong>Alcaldía de Santiago de Cali</strong><span>Secretaría de Salud &middot; Subgrupo ETV</span></div></div><div class="text-center mb-4"><img src="assets/img/branding/gemo-logo-color.png" alt="GEMO" class="gemo-mark-img"><h1 class="login-title">Nueva contraseña</h1><p class="text-muted mb-0">Cree una nueva contraseña para su cuenta.</p></div><?php if($exito): ?><div class="alert alert-success py-2"><?= htmlspecialchars($exito) ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-danger py-2"><?= htmlspecialchars($error) ?></div><?php endif; ?><form method="post" action="controllers/RecuperacionController.php" id="formNuevaPassword"><input type="hidden" name="accion" value="cambiar"><div class="mb-3"><label class="form-label">Nueva contraseña</label><div class="gemo-password-wrap"><input class="form-control form-control-lg" type="password" name="password_nueva" id="password_nueva" minlength="8" pattern="(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{8,}" autocomplete="new-password" required><button type="button" class="gemo-password-toggle" id="verNueva" aria-label="Mostrar contraseña"><i class="fas fa-eye"></i></button></div><small class="text-muted">Mínimo 8 caracteres, con mayúscula, minúscula, número y carácter especial.</small></div><div class="mb-4"><label class="form-label">Confirmar nueva contraseña</label><div class="gemo-password-wrap"><input class="form-control form-control-lg" type="password" name="password_confirmar" id="password_confirmar" minlength="8" autocomplete="new-password" required><button type="button" class="gemo-password-toggle" id="verConfirmar" aria-label="Mostrar contraseña"><i class="fas fa-eye"></i></button></div></div><button class="btn btn-gemo btn-lg w-100" type="submit">Guardar nueva contraseña</button></form></div></div><script>
(function(){
  function toggle(id,btnId){var c=document.getElementById(id),b=document.getElementById(btnId);if(!c||!b)return;b.addEventListener('click',function(){c.type=c.type==='password'?'text':'password';b.querySelector('i').classList.toggle('fa-eye',c.type==='password');b.querySelector('i').classList.toggle('fa-eye-slash',c.type==='text');c.focus();});}
  toggle('password_nueva','verNueva'); toggle('password_confirmar','verConfirmar');
  function bloquearPegado(id){var c=document.getElementById(id);if(!c)return;['paste','copy','cut','drop','contextmenu'].forEach(function(ev){c.addEventListener(ev,function(e){e.preventDefault();});});}
  bloquearPegado('password_nueva'); bloquearPegado('password_confirmar');
  document.getElementById('formNuevaPassword').addEventListener('submit',function(e){var a=document.getElementById('password_nueva'),b=document.getElementById('password_confirmar');var p=/^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{8,}$/;if(!p.test(a.value)){e.preventDefault();alert('La contraseña debe tener mínimo 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial.');a.focus();return;}if(a.value!==b.value){e.preventDefault();alert('Las contraseñas nuevas no coinciden.');b.focus();}});
})();
</script></body></html>