












BEGIN;


ALTER TABLE sitio_terreno
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE deposito
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE actividad_terreno
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;





ALTER TABLE sitio_terreno
    ALTER COLUMN id_sitio ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('sitio_terreno', 'id_sitio'),
              COALESCE((SELECT MAX(id_sitio) FROM sitio_terreno), 0) + 1, false);

ALTER TABLE deposito
    ALTER COLUMN id_deposito ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('deposito', 'id_deposito'),
              COALESCE((SELECT MAX(id_deposito) FROM deposito), 0) + 1, false);

ALTER TABLE actividad_terreno
    ALTER COLUMN id_actividad_terreno ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('actividad_terreno', 'id_actividad_terreno'),
              COALESCE((SELECT MAX(id_actividad_terreno) FROM actividad_terreno), 0) + 1, false);



ALTER TABLE sitio_barrio
    ALTER COLUMN id_sitio_barrio ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('sitio_barrio', 'id_sitio_barrio'),
              COALESCE((SELECT MAX(id_sitio_barrio) FROM sitio_barrio), 0) + 1, false);

COMMIT;
