-- =====================================================================
-- Migración: CRUD completo de Zoocriadero, Tipo Tanque,
-- Acciones Zoocriadero y Tanque (módulo Auxiliar de Zoocriadero, rol id_rol = 3)
-- Ejecutar sobre la base de datos GEMO ya creada con sql/bd_gemo.sql
-- (y después de sql/alter_auxiliar_zoocriadero.sql)
-- =====================================================================
--
-- Por qué es necesaria: "inhabilitar" (borrado lógico) requiere una
-- columna de estado que hoy no existe en estas 4 tablas, y para poder
-- crear registros desde la aplicación (sin asignar el id a mano) también
-- necesitan autoincremento. Es segura de ejecutar varias veces: no borra
-- ni pisa datos existentes.
-- =====================================================================

BEGIN;

-- 1. Columna de estado (borrado lógico) en las 4 tablas
ALTER TABLE zoocriadero
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tipo_tanque
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE actividad_zoocriadero
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tanque
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

-- 2. Autoincremento para poder crear registros desde la app
--    (antes había que asignar el id a mano). Se sincroniza la secuencia
--    con el mayor id que ya exista, para no chocar con los datos de
--    ejemplo cargados por alter_auxiliar_zoocriadero.sql.
ALTER TABLE zoocriadero
    ALTER COLUMN id_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('zoocriadero', 'id_zoocriadero'),
              COALESCE((SELECT MAX(id_zoocriadero) FROM zoocriadero), 0) + 1, false);

ALTER TABLE tipo_tanque
    ALTER COLUMN id_tipo_tanque ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tipo_tanque', 'id_tipo_tanque'),
              COALESCE((SELECT MAX(id_tipo_tanque) FROM tipo_tanque), 0) + 1, false);

ALTER TABLE actividad_zoocriadero
    ALTER COLUMN id_actividad_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('actividad_zoocriadero', 'id_actividad_zoocriadero'),
              COALESCE((SELECT MAX(id_actividad_zoocriadero) FROM actividad_zoocriadero), 0) + 1, false);

ALTER TABLE tanque
    ALTER COLUMN id_tanque ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tanque', 'id_tanque'),
              COALESCE((SELECT MAX(id_tanque) FROM tanque), 0) + 1, false);

-- 3. Permisos del nuevo menú para el rol 3 (Auxiliar Zoocriadero),
--    siguiendo el mismo mecanismo que ya usa el rol 4 (Auxiliar Terreno).
--    Si la tabla permiso_rol aún no existe en este ambiente (no se ha
--    aplicado sql/alter_permisos.sql), este bloque se omite sin error.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'permiso_rol') THEN
        INSERT INTO permiso_rol (id_rol, pagina, etiqueta) VALUES
        (3, 'zoocriaderos.php',        'Zoocriaderos'),
        (3, 'tanques.php',             'Tanques'),
        (3, 'tipos_tanque.php',        'Tipos de tanque'),
        (3, 'acciones_zoocriadero.php','Acciones del zoocriadero')
        ON CONFLICT (id_rol, pagina) DO NOTHING;
    END IF;
END $$;

COMMIT;
