-- =====================================================================
-- Migración: CRUD completo de Sitio, Depósito y Actividad Terreno
-- (módulo Auxiliar de Terreno, rol id_rol = 4)
-- Ejecutar sobre la base de datos GEMO ya creada con sql/bd_gemo.sql
-- =====================================================================
--
-- Por qué es necesaria: "inhabilitar" (borrado lógico) requiere una
-- columna de estado que hoy no existe en estas 3 tablas, y para poder
-- crear registros desde la aplicación (sin asignar el id a mano) también
-- necesitan autoincremento. Es segura de ejecutar aunque ya tengas datos
-- cargados con sql/alter_auxiliar_terreno.sql: no borra nada, solo agrega.
-- =====================================================================

BEGIN;

-- 1. Columna de estado (borrado lógico) en las 3 tablas
ALTER TABLE sitio_terreno
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE deposito
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE actividad_terreno
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

-- 2. Autoincremento para poder crear registros desde la app
--    (antes había que asignar el id a mano, igual que se corrigió antes
--     para id_seguimiento_zoo). Se sincroniza la secuencia con el mayor
--     id que ya exista, para no chocar con los datos de ejemplo.
ALTER TABLE sitio_terreno
    ALTER COLUMN id_sitio ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('sitio_terreno', 'id_sitio'),
              COALESCE((SELECT MAX(id_sitio) FROM sitio_terreno), 0) + 1, false);

ALTER TABLE deposito
    ALTER COLUMN id_deposito ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('deposito', 'id_deposito'),
              COALESCE((SELECT MAX(id_deposito) FROM deposito), 0) + 1, false);

ALTER TABLE actividad_terreno
    ALTER COLUMN id_actividad_terreno ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('actividad_terreno', 'id_actividad_terreno'),
              COALESCE((SELECT MAX(id_actividad_terreno) FROM actividad_terreno), 0) + 1, false);

-- 3. sitio_barrio también necesita autoincremento propio para poder
--    vincular barrios al crear/editar un sitio desde la app.
ALTER TABLE sitio_barrio
    ALTER COLUMN id_sitio_barrio ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('sitio_barrio', 'id_sitio_barrio'),
              COALESCE((SELECT MAX(id_sitio_barrio) FROM sitio_barrio), 0) + 1, false);

COMMIT;
