













BEGIN;


ALTER TABLE tipo_deposito
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;





ALTER TABLE tipo_deposito
    ALTER COLUMN id_tipo_deposito ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tipo_deposito', 'id_tipo_deposito'),
              COALESCE((SELECT MAX(id_tipo_deposito) FROM tipo_deposito), 0) + 1, false);





DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'permiso_rol') THEN
        INSERT INTO permiso_rol (id_rol, pagina, etiqueta) VALUES
        (4, 'tipos_deposito.php', 'Tipos de depósito')
        ON CONFLICT (id_rol, pagina) DO NOTHING;
    END IF;
END $$;

COMMIT;
