-- =====================================================================
-- Migración: CRUD completo de Tipo Depósito
-- (módulo Auxiliar de Terreno, rol id_rol = 4)
-- Ejecutar sobre la base de datos GEMO ya creada con sql/bd_gemo.sql
-- (y después de sql/alter_auxiliar_terreno.sql)
-- =====================================================================
--
-- Por qué es necesaria: "inhabilitar" (borrado lógico) requiere una
-- columna de estado que hoy no existe en tipo_deposito, y para poder
-- crear registros desde la aplicación (sin asignar el id a mano) también
-- necesita autoincremento. Es segura de ejecutar varias veces: no borra
-- ni pisa datos existentes.
-- =====================================================================

BEGIN;

-- 1. Columna de estado (borrado lógico)
ALTER TABLE tipo_deposito
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

-- 2. Autoincremento para poder crear registros desde la app
--    (antes había que asignar el id a mano). Se sincroniza la secuencia
--    con el mayor id que ya exista, para no chocar con los 4 valores
--    sembrados por alter_auxiliar_terreno.sql.
ALTER TABLE tipo_deposito
    ALTER COLUMN id_tipo_deposito ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tipo_deposito', 'id_tipo_deposito'),
              COALESCE((SELECT MAX(id_tipo_deposito) FROM tipo_deposito), 0) + 1, false);

-- 3. Permiso del nuevo menú para el rol 4 (Auxiliar Terreno), siguiendo
--    el mismo mecanismo que ya usan sitios.php, depositos.php, etc.
--    Si la tabla permiso_rol aún no existe en este ambiente (no se ha
--    aplicado sql/alter_permisos.sql), este bloque se omite sin error.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'permiso_rol') THEN
        INSERT INTO permiso_rol (id_rol, pagina, etiqueta) VALUES
        (4, 'tipos_deposito.php', 'Tipos de depósito')
        ON CONFLICT (id_rol, pagina) DO NOTHING;
    END IF;
END $$;

COMMIT;
