













BEGIN;


ALTER TABLE zoocriadero
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tipo_tanque
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE actividad_zoocriadero
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tanque
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;





ALTER TABLE zoocriadero
    ALTER COLUMN id_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('zoocriadero', 'id_zoocriadero'),
              COALESCE((SELECT MAX(id_zoocriadero) FROM zoocriadero), 0) + 1, false);

ALTER TABLE tipo_tanque
    ALTER COLUMN id_tipo_tanque ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tipo_tanque', 'id_tipo_tanque'),
              COALESCE((SELECT MAX(id_tipo_tanque) FROM tipo_tanque), 0) + 1, false);

ALTER TABLE actividad_zoocriadero
    ALTER COLUMN id_actividad_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('actividad_zoocriadero', 'id_actividad_zoocriadero'),
              COALESCE((SELECT MAX(id_actividad_zoocriadero) FROM actividad_zoocriadero), 0) + 1, false);

ALTER TABLE tanque
    ALTER COLUMN id_tanque ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tanque', 'id_tanque'),
              COALESCE((SELECT MAX(id_tanque) FROM tanque), 0) + 1, false);





DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'permiso_rol') THEN
        INSERT INTO permiso_rol (id_rol, pagina, etiqueta) VALUES
        (3, 'zoocriaderos.php',        'Zoocriaderos'),
        (3, 'tanques.php',             'Tanques'),
        (3, 'tipos_tanque.php',        'Tipos de tanque'),
        (3, 'acciones_zoocriadero.php','Acciones del zoocriadero')
        ON CONFLICT (id_rol, pagina) DO NOTHING;
    END IF;
END $$;

COMMIT;
