-- =====================================================================
-- Migración: módulo de Auxiliar de Zoocriadero (rol id_rol = 3)
-- Ejecutar sobre la base de datos GEMO ya creada con sql/bd_gemo.sql
-- =====================================================================

BEGIN;

-- 1. Nuevo parámetro fisicoquímico: cloro
ALTER TABLE seguimiento_zoocriadero
    ADD COLUMN IF NOT EXISTS cloro NUMERIC(4,2);

-- 2. "peces_nacidos" pasa a llamarse "alevines_nacidos"
ALTER TABLE seguimiento_zoocriadero
    RENAME COLUMN peces_nacidos TO alevines_nacidos;

-- 3. Separar mortalidad por sexo (antes era un solo campo "peces_muertos")
ALTER TABLE seguimiento_zoocriadero
    ADD COLUMN IF NOT EXISTS muertos_macho  SMALLINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS muertos_hembra SMALLINT DEFAULT 0;

UPDATE seguimiento_zoocriadero
   SET muertos_macho = COALESCE(peces_muertos, 0)
 WHERE peces_muertos IS NOT NULL;

ALTER TABLE seguimiento_zoocriadero
    DROP COLUMN IF EXISTS peces_muertos;

-- 4. Las actividades ahora se seleccionan con checkboxes (varias por registro),
--    por lo que se reemplaza la FK única por una tabla intermedia.
ALTER TABLE seguimiento_zoocriadero
    DROP CONSTRAINT IF EXISTS fk_seguimiento_zoo_actividad;

ALTER TABLE seguimiento_zoocriadero
    DROP COLUMN IF EXISTS id_actividad_zoocriadero;

CREATE TABLE IF NOT EXISTS seguimiento_zoo_actividad (
    id_seguimiento_zoo       SMALLINT NOT NULL,
    id_actividad_zoocriadero SMALLINT NOT NULL,
    CONSTRAINT pk_seguimiento_zoo_actividad PRIMARY KEY (id_seguimiento_zoo, id_actividad_zoocriadero),
    CONSTRAINT fk_szact_seguimiento FOREIGN KEY (id_seguimiento_zoo)
        REFERENCES seguimiento_zoocriadero (id_seguimiento_zoo),
    CONSTRAINT fk_szact_actividad FOREIGN KEY (id_actividad_zoocriadero)
        REFERENCES actividad_zoocriadero (id_actividad_zoocriadero)
);

-- 5. id_seguimiento_zoo pasa a autogenerarse (antes se debía asignar a mano)
ALTER TABLE seguimiento_zoocriadero
    ALTER COLUMN id_seguimiento_zoo ADD GENERATED BY DEFAULT AS IDENTITY;

-- 6. Catálogos que pide el formulario
INSERT INTO tipo_tanque (id_tipo_tanque, descripcion) VALUES
    (1, 'Siembra'),
    (2, 'Reproducción'),
    (3, 'Alevines'),
    (4, 'Reserva')
ON CONFLICT (id_tipo_tanque) DO NOTHING;

INSERT INTO actividad_zoocriadero (id_actividad_zoocriadero, nombre) VALUES
    (1, 'Limpieza'),
    (2, 'Aspirado'),
    (3, 'Ajuste de nivel de agua')
ON CONFLICT (id_actividad_zoocriadero) DO NOTHING;

-- 7. Datos de ejemplo mínimos para poder probar el formulario
--    (bórralos o ajústalos cuando exista el módulo real de zoocriaderos/tanques).
INSERT INTO comuna (id_comuna, nombre) VALUES (1, 'Comuna 1')
    ON CONFLICT (id_comuna) DO NOTHING;

INSERT INTO barrio (id_barrio, nombre, id_comuna) VALUES (1, 'Barrio Centro', 1)
    ON CONFLICT (id_barrio) DO NOTHING;

INSERT INTO zoocriadero (id_zoocriadero, direccion, id_usuario, id_barrio)
    VALUES (1, 'Sede principal', 1, 1)
    ON CONFLICT (id_zoocriadero) DO NOTHING;

INSERT INTO tanque (id_tanque, id_zoocriadero, id_tipo_tanque, estado) VALUES
    (1, 1, 1, 'Activo'),
    (2, 1, 2, 'Activo'),
    (3, 1, 3, 'Activo'),
    (4, 1, 4, 'Activo')
ON CONFLICT (id_tanque) DO NOTHING;

COMMIT;
