--
-- PostgreSQL database dump
--

\restrict V3Eu0M2kgdZ2aqhOThFr3zLK6Bd6S3kflvEVKANev15Q9WlFFtONJVjYDcubHQb

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-19 17:15:40

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 252 (class 1255 OID 41526)
-- Name: sp_registrar_seguimiento_terreno(integer, date, time without time zone, text[], integer); Type: PROCEDURE; Schema: public; Owner: postgres
--

CREATE PROCEDURE public.sp_registrar_seguimiento_terreno(IN p_id_seguimiento integer, IN p_fecha date, IN p_hora time without time zone, IN p_actividades text[], IN p_usuario_creador integer)
    LANGUAGE plpgsql
    AS $$
BEGIN
    INSERT INTO tabla_seguimiento_principal (
        id_seguimiento, 
        fecha, 
        hora
    ) VALUES (
        p_id_seguimiento, 
        p_fecha, 
        p_hora
    );

    
    INSERT INTO tabla_actividades_terreno (
        id_seguimiento,
        fecha,
        hora,
        actividades_cargadas,
        usuario_creador
    ) VALUES (
        p_id_seguimiento,
        p_fecha,
        p_hora,
        array_to_string(p_actividades, ', '),
        p_usuario_creador
    );

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Error al registrar el seguimiento en terreno: %', SQLERRM;
END;
$$;


ALTER PROCEDURE public.sp_registrar_seguimiento_terreno(IN p_id_seguimiento integer, IN p_fecha date, IN p_hora time without time zone, IN p_actividades text[], IN p_usuario_creador integer) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 41527)
-- Name: actividad_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad_terreno (
    id_actividad_terreno smallint NOT NULL,
    nombre character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.actividad_terreno OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 41534)
-- Name: actividad_terreno_id_actividad_terreno_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad_terreno ALTER COLUMN id_actividad_terreno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_terreno_id_actividad_terreno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 41535)
-- Name: actividad_zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad_zoocriadero (
    id_actividad_zoocriadero smallint NOT NULL,
    nombre character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.actividad_zoocriadero OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 41542)
-- Name: actividad_zoocriadero_id_actividad_zoocriadero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad_zoocriadero ALTER COLUMN id_actividad_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_zoocriadero_id_actividad_zoocriadero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 41543)
-- Name: barrio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barrio (
    id_barrio smallint NOT NULL,
    nombre character varying(120) NOT NULL,
    id_comuna smallint NOT NULL
);


ALTER TABLE public.barrio OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 41549)
-- Name: comuna; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comuna (
    id_comuna smallint NOT NULL,
    nombre character varying(120) NOT NULL
);


ALTER TABLE public.comuna OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 41554)
-- Name: deposito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deposito (
    id_deposito smallint NOT NULL,
    id_sitio smallint NOT NULL,
    id_tipo_deposito smallint NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.deposito OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 41562)
-- Name: deposito_id_deposito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deposito ALTER COLUMN id_deposito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposito_id_deposito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 41817)
-- Name: password_reset_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_codes (
    id_reset integer NOT NULL,
    id_usuario smallint NOT NULL,
    codigo_hash character varying(255) NOT NULL,
    expira_en timestamp without time zone NOT NULL,
    intentos smallint DEFAULT 0 NOT NULL,
    verificado boolean DEFAULT false NOT NULL,
    usado_en timestamp without time zone,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.password_reset_codes OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 41816)
-- Name: password_reset_codes_id_reset_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_codes ALTER COLUMN id_reset ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_codes_id_reset_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 41563)
-- Name: permiso_rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permiso_rol (
    id_permiso smallint NOT NULL,
    id_rol smallint NOT NULL,
    pagina character varying(100) NOT NULL,
    etiqueta character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.permiso_rol OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 41572)
-- Name: permiso_rol_id_permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permiso_rol ALTER COLUMN id_permiso ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.permiso_rol_id_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 41573)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol smallint NOT NULL,
    nombre_rol character varying(50) NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 41578)
-- Name: seguimiento_terreno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seguimiento_terreno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.seguimiento_terreno_id_seq OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 41579)
-- Name: seguimiento_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_terreno (
    id_seguimiento_terreno smallint DEFAULT nextval('public.seguimiento_terreno_id_seq'::regclass) NOT NULL,
    id_deposito smallint NOT NULL,
    id_usuario smallint NOT NULL,
    fecha date NOT NULL,
    id_actividad_terreno smallint NOT NULL,
    ph numeric(3,1),
    temperatura numeric(4,1),
    larvas_aedes smallint,
    pupas smallint,
    larvas_culex smallint
);


ALTER TABLE public.seguimiento_terreno OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 41588)
-- Name: seguimiento_zoo_actividad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_zoo_actividad (
    id_seguimiento_zoo smallint NOT NULL,
    id_actividad_zoocriadero smallint NOT NULL
);


ALTER TABLE public.seguimiento_zoo_actividad OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 41593)
-- Name: seguimiento_zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_zoocriadero (
    id_seguimiento_zoo smallint NOT NULL,
    id_tanque smallint NOT NULL,
    id_usuario smallint NOT NULL,
    fecha date NOT NULL,
    ph numeric(3,1),
    temperatura numeric(4,1),
    alevines_nacidos smallint,
    observaciones text,
    cloro numeric(4,2),
    muertos_macho smallint DEFAULT 0,
    muertos_hembra smallint DEFAULT 0
);


ALTER TABLE public.seguimiento_zoocriadero OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 41604)
-- Name: seguimiento_zoocriadero_id_seguimiento_zoo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seguimiento_zoocriadero ALTER COLUMN id_seguimiento_zoo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguimiento_zoocriadero_id_seguimiento_zoo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 41605)
-- Name: sitio_barrio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sitio_barrio (
    id_sitio_barrio smallint NOT NULL,
    id_sitio smallint NOT NULL,
    id_barrio smallint NOT NULL
);


ALTER TABLE public.sitio_barrio OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 41611)
-- Name: sitio_barrio_id_sitio_barrio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sitio_barrio ALTER COLUMN id_sitio_barrio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sitio_barrio_id_sitio_barrio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 41612)
-- Name: sitio_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sitio_terreno (
    id_sitio smallint NOT NULL,
    direccion character varying(50),
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.sitio_terreno OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 41618)
-- Name: sitio_terreno_id_sitio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sitio_terreno ALTER COLUMN id_sitio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sitio_terreno_id_sitio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 41619)
-- Name: tanque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tanque (
    id_tanque smallint NOT NULL,
    id_zoocriadero smallint NOT NULL,
    id_tipo_tanque smallint NOT NULL,
    estado character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tanque OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 41628)
-- Name: tanque_id_tanque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tanque ALTER COLUMN id_tanque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tanque_id_tanque_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 41629)
-- Name: tipo_deposito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_deposito (
    id_tipo_deposito smallint NOT NULL,
    descripcion character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tipo_deposito OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 41636)
-- Name: tipo_deposito_id_tipo_deposito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_deposito ALTER COLUMN id_tipo_deposito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_deposito_id_tipo_deposito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 41637)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_documento (
    id_tipo_documento smallint NOT NULL,
    nombre_tipo_documento character varying(120) NOT NULL
);


ALTER TABLE public.tipo_documento OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 41642)
-- Name: tipo_tanque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_tanque (
    id_tipo_tanque smallint NOT NULL,
    descripcion character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tipo_tanque OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 41649)
-- Name: tipo_tanque_id_tipo_tanque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_tanque ALTER COLUMN id_tipo_tanque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_tanque_id_tipo_tanque_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 41650)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario smallint NOT NULL,
    id_rol smallint NOT NULL,
    documento character varying(50) NOT NULL,
    nombres character varying(50) NOT NULL,
    apellidos character varying(50) NOT NULL,
    id_tipo_documento integer NOT NULL,
    "contraseña" character varying(255) NOT NULL,
    correo character varying(150) NOT NULL,
    fecha_nacimiento date NOT NULL,
    telefono character varying(20) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 41667)
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 41668)
-- Name: zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zoocriadero (
    id_zoocriadero smallint NOT NULL,
    direccion character varying(50) NOT NULL,
    id_usuario smallint NOT NULL,
    id_barrio smallint NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.zoocriadero OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 41677)
-- Name: zoocriadero_id_zoocriadero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zoocriadero ALTER COLUMN id_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zoocriadero_id_zoocriadero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5171 (class 0 OID 41527)
-- Dependencies: 219
-- Data for Name: actividad_terreno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad_terreno (id_actividad_terreno, nombre, activo) FROM stdin;
1	Siembra	t
3	Seguimiento	t
4	Resiembra	t
\.


--
-- TOC entry 5173 (class 0 OID 41535)
-- Dependencies: 221
-- Data for Name: actividad_zoocriadero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad_zoocriadero (id_actividad_zoocriadero, nombre, activo) FROM stdin;
1	Limpieza	t
2	Aspirado	t
3	Ajuste de nivel de agua	t
\.


--
-- TOC entry 5175 (class 0 OID 41543)
-- Dependencies: 223
-- Data for Name: barrio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.barrio (id_barrio, nombre, id_comuna) FROM stdin;
1	Terrón Colorado	1
2	Vista Hermosa	1
3	Aguacatal	1
4	Palermo	1
5	Sector Patiño	1
6	La Flora	2
7	Vipasa	2
8	Altos de Menga	2
9	San Vicente	2
10	El Bosque	2
11	Santa Mónica	2
12	San Antonio	3
13	El Peñón	3
14	San Cayetano	3
15	Libertadores	3
16	La Merced	3
17	Nacional	3
18	Manzanares	4
19	Salomia	4
20	San Francisco	4
21	Flora Industrial	4
22	Las Delicias	4
23	Chiminangos	5
24	Los Andes	5
25	Sena	5
26	Rivera	5
27	Paseo de los Almendros	5
28	Floralia	6
29	Petecuy	6
30	San Luis	6
31	Fonaviemcali	6
32	Paso del Comercio	6
33	Alfonso López	7
34	Puerto Mallarino	7
35	Siete de Agosto	7
36	Los Pinos	7
37	San Marino	7
38	Las Américas	8
39	Benjamín Herrera	8
40	Chapinero	8
41	Municipal	8
42	Sindical	8
43	La Base	8
44	Aranjuez	9
45	Sucre	9
46	Obrero	9
47	San Bosco	9
48	Guayaquil	9
49	Alameda	9
50	Santa Elena	10
51	Colseguros	10
52	Departamental	10
53	Panamericano	10
54	San Judas Tadeo	10
55	San Carlos	11
56	La Independencia	11
57	Agua Blanca	11
58	León XIII	11
59	Los Conquistadores	11
60	Villanueva	12
61	Eduardo Santos	12
62	Asturias	12
63	Nueva Floresta	12
64	Doce de Octubre	12
65	El Poblado	13
66	Los Lagos	13
67	Charco Azul	13
68	Villablanca	13
69	El Pondaje	13
70	Puertas del Sol	14
71	Manuela Beltrán	14
72	Las Orquídeas	14
73	Alirio Mora Beltrán	14
74	Marroquín	14
75	El Retiro	15
76	El Vallado	15
77	Ciudad Córdoba	15
78	Mojica	15
79	Comuneros	15
80	Mariano Ramos	16
81	República de Israel	16
82	Unión de Vivienda Popular	16
83	Antonio Nariño	16
84	El Limonar	17
85	Ciudad Capri	17
86	Valle del Lili	17
87	San Joaquín	17
88	El Ingenio	17
89	Mayapán	17
90	Las Vegas	17
91	Meléndez	18
92	Los Chorros	18
93	Alto Nápoles	18
94	Buenos Aires	18
95	Colinas del Sur	18
96	San Fernando	19
97	Miraflores	19
98	Tequendama	19
99	Bellavista	19
100	Nueva Granada	19
101	Cañaveralejo	19
102	Cuarto de Legua	19
103	Eucarístico	19
104	Siloé	20
105	Belisario Betancur	20
106	Lleras Camargo	20
107	Tierra Blanca	20
108	La Sultana	20
109	Desepaz	21
110	Potrero Grande	21
111	Valle Grande	21
112	Compartir	21
113	Pízamos	21
114	Ciudad Jardín	22
115	Pance	22
116	Alférez Real	22
\.


--
-- TOC entry 5176 (class 0 OID 41549)
-- Dependencies: 224
-- Data for Name: comuna; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comuna (id_comuna, nombre) FROM stdin;
1	Comuna 1
2	Comuna 2
3	Comuna 3
4	Comuna 4
5	Comuna 5
6	Comuna 6
7	Comuna 7
8	Comuna 8
9	Comuna 9
10	Comuna 10
11	Comuna 11
12	Comuna 12
13	Comuna 13
14	Comuna 14
15	Comuna 15
16	Comuna 16
17	Comuna 17
18	Comuna 18
19	Comuna 19
20	Comuna 20
21	Comuna 21
22	Comuna 22
\.


--
-- TOC entry 5177 (class 0 OID 41554)
-- Dependencies: 225
-- Data for Name: deposito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deposito (id_deposito, id_sitio, id_tipo_deposito, activo) FROM stdin;
1	1	1	t
2	1	2	t
3	2	3	t
4	2	3	t
\.


--
-- TOC entry 5203 (class 0 OID 41817)
-- Dependencies: 251
-- Data for Name: password_reset_codes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_codes (id_reset, id_usuario, codigo_hash, expira_en, intentos, verificado, usado_en, creado_en) FROM stdin;
\.


--
-- TOC entry 5179 (class 0 OID 41563)
-- Dependencies: 227
-- Data for Name: permiso_rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permiso_rol (id_permiso, id_rol, pagina, etiqueta, activo) FROM stdin;
1	1	dashboard.php	Panel principal	t
2	1	usuarios.php	Usuarios	t
3	1	registrar_usuario.php	Registrar usuario	t
4	1	reportes.php	Reportes	t
5	1	informacion_personal.php	Informaci¢n personal	t
6	2	inicio.php	Inicio	t
7	2	reportes.php	Reportes	t
8	2	informacion_personal.php	Informaci¢n personal	t
9	3	inicio.php	Inicio	t
10	3	mis_registros.php	Mis registros	t
11	3	registrar_seguimiento.php	Registrar seguimiento	t
12	3	informacion_personal.php	Informaci¢n personal	t
13	4	inicio.php	Inicio	t
16	4	estadisticas.php	Estad¡sticas	t
17	4	mis_registros.php	Mis registros	t
18	4	registrar_seguimiento.php	Registrar seguimiento	t
19	4	reportes.php	Reportes	t
21	4	Formulario_seguimiento.php	Formulario de seguimiento	t
22	4	informacion_personal.php	Informaci¢n personal	t
23	5	inicio.php	Inicio	t
24	5	reportes.php	Reportes	t
25	5	informacion_personal.php	Informaci¢n personal	t
26	6	dashboard.php	Panel principal	t
27	6	auditoria_terreno.php	Auditor¡a de terreno	t
28	6	informacion_personal.php	Informaci¢n personal	t
29	6	permisos.php	Gesti¢n de permisos	t
34	1	reportes_zoocriadero.php	Reportes del zoocriadero	t
35	1	reportes_terreno.php	Reportes de terreno	t
37	5	sitios.php	Sitios	t
38	5	depositos.php	Depósitos	t
39	5	tipos_deposito.php	Tipos de depósito	t
40	5	actividades.php	Actividades	t
41	2	zoocriaderos.php	Zoocriaderos	t
42	2	tanques.php	Tanques	t
43	2	tipos_tanque.php	Tipos de tanque	t
44	2	acciones_zoocriadero.php	Acciones del zoocriadero	t
45	1	sitios.php	Sitios	t
46	1	depositos.php	Depósitos	t
47	1	tipos_deposito.php	Tipos de depósito	t
48	1	actividades.php	Actividades	t
49	1	zoocriaderos.php	Zoocriaderos	t
50	1	tanques.php	Tanques	t
51	1	tipos_tanque.php	Tipos de tanque	t
52	1	acciones_zoocriadero.php	Acciones del zoocriadero	t
\.


--
-- TOC entry 5181 (class 0 OID 41573)
-- Dependencies: 229
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id_rol, nombre_rol) FROM stdin;
1	Administrador del Sistema
3	Auxiliar Zoocriadero
4	Auxiliar Terrero
2	Coordinador Zoocriadero
5	Coordinador Terreno
6	Super Administrador
\.


--
-- TOC entry 5183 (class 0 OID 41579)
-- Dependencies: 231
-- Data for Name: seguimiento_terreno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seguimiento_terreno (id_seguimiento_terreno, id_deposito, id_usuario, fecha, id_actividad_terreno, ph, temperatura, larvas_aedes, pupas, larvas_culex) FROM stdin;
2	1	1	2026-09-14	1	4.0	13.8	12	12	12
3	1	1	2026-09-14	1	12.0	12.0	12	12	0
\.


--
-- TOC entry 5184 (class 0 OID 41588)
-- Dependencies: 232
-- Data for Name: seguimiento_zoo_actividad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seguimiento_zoo_actividad (id_seguimiento_zoo, id_actividad_zoocriadero) FROM stdin;
1	1
1	2
\.


--
-- TOC entry 5185 (class 0 OID 41593)
-- Dependencies: 233
-- Data for Name: seguimiento_zoocriadero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seguimiento_zoocriadero (id_seguimiento_zoo, id_tanque, id_usuario, fecha, ph, temperatura, alevines_nacidos, observaciones, cloro, muertos_macho, muertos_hembra) FROM stdin;
1	1	6	2026-09-11	14.0	20.0	100	\N	20.00	2	3
\.


--
-- TOC entry 5187 (class 0 OID 41605)
-- Dependencies: 235
-- Data for Name: sitio_barrio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sitio_barrio (id_sitio_barrio, id_sitio, id_barrio) FROM stdin;
1	1	1
2	1	1
3	2	1
\.


--
-- TOC entry 5189 (class 0 OID 41612)
-- Dependencies: 237
-- Data for Name: sitio_terreno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sitio_terreno (id_sitio, direccion, activo) FROM stdin;
1	calle 1a oeste #79a 10	t
2	Carrera 15 # 8-30	t
\.


--
-- TOC entry 5191 (class 0 OID 41619)
-- Dependencies: 239
-- Data for Name: tanque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tanque (id_tanque, id_zoocriadero, id_tipo_tanque, estado, activo) FROM stdin;
1	1	1	Activo	t
2	1	2	Activo	t
3	1	3	Activo	t
4	1	4	Activo	t
\.


--
-- TOC entry 5193 (class 0 OID 41629)
-- Dependencies: 241
-- Data for Name: tipo_deposito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_deposito (id_tipo_deposito, descripcion, activo) FROM stdin;
1	Tanque bajo	t
2	Tanque elevado	t
3	Llanta	t
4	Florero / Materero	t
5	Botella / Envase	t
6	Canaleta	t
7	Otro	t
\.


--
-- TOC entry 5195 (class 0 OID 41637)
-- Dependencies: 243
-- Data for Name: tipo_documento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_documento (id_tipo_documento, nombre_tipo_documento) FROM stdin;
1	Cédula de Ciudadanía
2	Cédula de Extranjería
3	Pasaporte
4	Permiso por Protección Temporal (PPT)
\.


--
-- TOC entry 5196 (class 0 OID 41642)
-- Dependencies: 244
-- Data for Name: tipo_tanque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_tanque (id_tipo_tanque, descripcion, activo) FROM stdin;
1	Siembra	t
2	Reproducción	t
3	Alevines	t
4	Reserva	t
\.


--
-- TOC entry 5198 (class 0 OID 41650)
-- Dependencies: 246
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, id_rol, documento, nombres, apellidos, id_tipo_documento, "contraseña", correo, fecha_nacimiento, telefono, activo) FROM stdin;
1	4	1110368987	Jhon Alejandro	Vanegas Morcillo	1	$2b$10$U1HoPj0vzA//W82oSP0EwucivCxh.cEre42WSmHVdu7btQLmPk6gK	jhonalejandrovanegas2007@gmail.com	2007-10-03	3165758299	t
2	3	1150684911	Maria Elena	Guzman Perez	1	$2b$10$X4kQoG8fO3sLIWzvhNJ/PuTt4aBO1pIA.t.pdabZMbNIqBsB1tsEO	mariaguzman0040@gmail.com	2008-08-09	3226897067	t
3	5	1194860512	Kevin Santiago	Morales Cardenas	1	$2b$10$fzekK.GJki/LcWHH7YEn1eVxE8rbi7BLekRa8X168dozciD1rlrD2	k0john.s5321@gmail.com	2008-03-19	3186556253	t
4	2	1062014769	Luna Alejandra	Cossio Valencia	1	$2b$10$v7.yzdjzU6kXhAnEXvfpLuwys4AlKzTncDf0EhNXymI5vivOKuFyC	moralesantiago918@gmail.com	2008-01-03	3157637518	t
5	1	1110042737	Nicolas	Bonilla Grueso	1	$2b$10$9Zor5dD6SdkwlTJwPbq1we2OoMunKGUj5gpGDCk/eE7JTL2tB7BsO	nikobongru@gmail.com	2007-05-23	3185418575	t
6	6	1062014768	Kevin Alfonso	Morales Vargas	1	$2b$10$Rt7PCgPoq809nFXNxD6hBe4kdUTgElqBf28zYZWx5O95hIV3C8XCy	kevin43grlv@gmail.com	2008-03-19	3226970638	t
\.


--
-- TOC entry 5200 (class 0 OID 41668)
-- Dependencies: 248
-- Data for Name: zoocriadero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zoocriadero (id_zoocriadero, direccion, id_usuario, id_barrio, activo) FROM stdin;
1	Sede principal	6	1	t
\.


--
-- TOC entry 5209 (class 0 OID 0)
-- Dependencies: 220
-- Name: actividad_terreno_id_actividad_terreno_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividad_terreno_id_actividad_terreno_seq', 4, true);


--
-- TOC entry 5210 (class 0 OID 0)
-- Dependencies: 222
-- Name: actividad_zoocriadero_id_actividad_zoocriadero_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividad_zoocriadero_id_actividad_zoocriadero_seq', 4, false);


--
-- TOC entry 5211 (class 0 OID 0)
-- Dependencies: 226
-- Name: deposito_id_deposito_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deposito_id_deposito_seq', 4, true);


--
-- TOC entry 5212 (class 0 OID 0)
-- Dependencies: 250
-- Name: password_reset_codes_id_reset_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_codes_id_reset_seq', 1, false);


--
-- TOC entry 5213 (class 0 OID 0)
-- Dependencies: 228
-- Name: permiso_rol_id_permiso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permiso_rol_id_permiso_seq', 52, true);


--
-- TOC entry 5214 (class 0 OID 0)
-- Dependencies: 230
-- Name: seguimiento_terreno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seguimiento_terreno_id_seq', 3, true);


--
-- TOC entry 5215 (class 0 OID 0)
-- Dependencies: 234
-- Name: seguimiento_zoocriadero_id_seguimiento_zoo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seguimiento_zoocriadero_id_seguimiento_zoo_seq', 1, true);


--
-- TOC entry 5216 (class 0 OID 0)
-- Dependencies: 236
-- Name: sitio_barrio_id_sitio_barrio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sitio_barrio_id_sitio_barrio_seq', 3, true);


--
-- TOC entry 5217 (class 0 OID 0)
-- Dependencies: 238
-- Name: sitio_terreno_id_sitio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sitio_terreno_id_sitio_seq', 2, true);


--
-- TOC entry 5218 (class 0 OID 0)
-- Dependencies: 240
-- Name: tanque_id_tanque_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tanque_id_tanque_seq', 5, false);


--
-- TOC entry 5219 (class 0 OID 0)
-- Dependencies: 242
-- Name: tipo_deposito_id_tipo_deposito_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_deposito_id_tipo_deposito_seq', 8, false);


--
-- TOC entry 5220 (class 0 OID 0)
-- Dependencies: 245
-- Name: tipo_tanque_id_tipo_tanque_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_tanque_id_tipo_tanque_seq', 5, false);


--
-- TOC entry 5221 (class 0 OID 0)
-- Dependencies: 247
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 6, true);


--
-- TOC entry 5222 (class 0 OID 0)
-- Dependencies: 249
-- Name: zoocriadero_id_zoocriadero_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zoocriadero_id_zoocriadero_seq', 2, false);


--
-- TOC entry 5003 (class 2606 OID 41831)
-- Name: password_reset_codes password_reset_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT password_reset_codes_pkey PRIMARY KEY (id_reset);


--
-- TOC entry 4959 (class 2606 OID 41679)
-- Name: actividad_terreno pk_actividad_terreno; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_terreno
    ADD CONSTRAINT pk_actividad_terreno PRIMARY KEY (id_actividad_terreno);


--
-- TOC entry 4961 (class 2606 OID 41681)
-- Name: actividad_zoocriadero pk_actividad_zoocriadero; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_zoocriadero
    ADD CONSTRAINT pk_actividad_zoocriadero PRIMARY KEY (id_actividad_zoocriadero);


--
-- TOC entry 4963 (class 2606 OID 41683)
-- Name: barrio pk_barrio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barrio
    ADD CONSTRAINT pk_barrio PRIMARY KEY (id_barrio);


--
-- TOC entry 4965 (class 2606 OID 41685)
-- Name: comuna pk_comuna; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comuna
    ADD CONSTRAINT pk_comuna PRIMARY KEY (id_comuna);


--
-- TOC entry 4967 (class 2606 OID 41687)
-- Name: deposito pk_deposito; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT pk_deposito PRIMARY KEY (id_deposito);


--
-- TOC entry 4969 (class 2606 OID 41689)
-- Name: permiso_rol pk_permiso_rol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso_rol
    ADD CONSTRAINT pk_permiso_rol PRIMARY KEY (id_permiso);


--
-- TOC entry 4973 (class 2606 OID 41691)
-- Name: rol pk_rol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT pk_rol PRIMARY KEY (id_rol);


--
-- TOC entry 4975 (class 2606 OID 41693)
-- Name: seguimiento_terreno pk_seguimiento_terreno; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT pk_seguimiento_terreno PRIMARY KEY (id_seguimiento_terreno);


--
-- TOC entry 4977 (class 2606 OID 41695)
-- Name: seguimiento_zoo_actividad pk_seguimiento_zoo_actividad; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoo_actividad
    ADD CONSTRAINT pk_seguimiento_zoo_actividad PRIMARY KEY (id_seguimiento_zoo, id_actividad_zoocriadero);


--
-- TOC entry 4979 (class 2606 OID 41697)
-- Name: seguimiento_zoocriadero pk_seguimiento_zoocriadero; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT pk_seguimiento_zoocriadero PRIMARY KEY (id_seguimiento_zoo);


--
-- TOC entry 4981 (class 2606 OID 41699)
-- Name: sitio_barrio pk_sitio_barrio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_barrio
    ADD CONSTRAINT pk_sitio_barrio PRIMARY KEY (id_sitio_barrio);


--
-- TOC entry 4983 (class 2606 OID 41701)
-- Name: sitio_terreno pk_sitio_terreno; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_terreno
    ADD CONSTRAINT pk_sitio_terreno PRIMARY KEY (id_sitio);


--
-- TOC entry 4985 (class 2606 OID 41703)
-- Name: tanque pk_tanque; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT pk_tanque PRIMARY KEY (id_tanque);


--
-- TOC entry 4987 (class 2606 OID 41705)
-- Name: tipo_deposito pk_tipo_deposito; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_deposito
    ADD CONSTRAINT pk_tipo_deposito PRIMARY KEY (id_tipo_deposito);


--
-- TOC entry 4989 (class 2606 OID 41707)
-- Name: tipo_documento pk_tipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_documento
    ADD CONSTRAINT pk_tipo_documento PRIMARY KEY (id_tipo_documento);


--
-- TOC entry 4991 (class 2606 OID 41709)
-- Name: tipo_tanque pk_tipo_tanque; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_tanque
    ADD CONSTRAINT pk_tipo_tanque PRIMARY KEY (id_tipo_tanque);


--
-- TOC entry 4993 (class 2606 OID 41711)
-- Name: usuario pk_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT pk_usuario PRIMARY KEY (id_usuario);


--
-- TOC entry 4999 (class 2606 OID 41713)
-- Name: zoocriadero pk_zoocriadero; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT pk_zoocriadero PRIMARY KEY (id_zoocriadero);


--
-- TOC entry 4971 (class 2606 OID 41715)
-- Name: permiso_rol uq_permiso_rol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso_rol
    ADD CONSTRAINT uq_permiso_rol UNIQUE (id_rol, pagina);


--
-- TOC entry 4995 (class 2606 OID 41717)
-- Name: usuario uq_usuario_documento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uq_usuario_documento UNIQUE (documento);


--
-- TOC entry 4997 (class 2606 OID 41719)
-- Name: usuario usuario_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_correo_key UNIQUE (correo);


--
-- TOC entry 5000 (class 1259 OID 41838)
-- Name: idx_password_reset_expira; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_password_reset_expira ON public.password_reset_codes USING btree (expira_en);


--
-- TOC entry 5001 (class 1259 OID 41837)
-- Name: idx_password_reset_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_password_reset_usuario ON public.password_reset_codes USING btree (id_usuario);


--
-- TOC entry 5004 (class 2606 OID 41720)
-- Name: barrio fk_barrio_comuna; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barrio
    ADD CONSTRAINT fk_barrio_comuna FOREIGN KEY (id_comuna) REFERENCES public.comuna(id_comuna);


--
-- TOC entry 5005 (class 2606 OID 41725)
-- Name: deposito fk_deposito_sitio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT fk_deposito_sitio FOREIGN KEY (id_sitio) REFERENCES public.sitio_terreno(id_sitio);


--
-- TOC entry 5006 (class 2606 OID 41730)
-- Name: deposito fk_deposito_tipo_deposito; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT fk_deposito_tipo_deposito FOREIGN KEY (id_tipo_deposito) REFERENCES public.tipo_deposito(id_tipo_deposito);


--
-- TOC entry 5023 (class 2606 OID 41832)
-- Name: password_reset_codes fk_password_reset_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT fk_password_reset_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;


--
-- TOC entry 5007 (class 2606 OID 41735)
-- Name: permiso_rol fk_permiso_rol_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso_rol
    ADD CONSTRAINT fk_permiso_rol_rol FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- TOC entry 5008 (class 2606 OID 41740)
-- Name: seguimiento_terreno fk_seguimiento_terreno_actividad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT fk_seguimiento_terreno_actividad FOREIGN KEY (id_actividad_terreno) REFERENCES public.actividad_terreno(id_actividad_terreno);


--
-- TOC entry 5009 (class 2606 OID 41745)
-- Name: seguimiento_terreno fk_seguimiento_terreno_deposito; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT fk_seguimiento_terreno_deposito FOREIGN KEY (id_deposito) REFERENCES public.deposito(id_deposito);


--
-- TOC entry 5010 (class 2606 OID 41750)
-- Name: seguimiento_terreno fk_seguimiento_terreno_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT fk_seguimiento_terreno_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 5013 (class 2606 OID 41755)
-- Name: seguimiento_zoocriadero fk_seguimiento_zoo_tanque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT fk_seguimiento_zoo_tanque FOREIGN KEY (id_tanque) REFERENCES public.tanque(id_tanque);


--
-- TOC entry 5014 (class 2606 OID 41760)
-- Name: seguimiento_zoocriadero fk_seguimiento_zoo_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT fk_seguimiento_zoo_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 5015 (class 2606 OID 41765)
-- Name: sitio_barrio fk_sitio_barrio_barrio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_barrio
    ADD CONSTRAINT fk_sitio_barrio_barrio FOREIGN KEY (id_barrio) REFERENCES public.barrio(id_barrio);


--
-- TOC entry 5016 (class 2606 OID 41770)
-- Name: sitio_barrio fk_sitio_barrio_sitio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio_barrio
    ADD CONSTRAINT fk_sitio_barrio_sitio FOREIGN KEY (id_sitio) REFERENCES public.sitio_terreno(id_sitio);


--
-- TOC entry 5011 (class 2606 OID 41775)
-- Name: seguimiento_zoo_actividad fk_szact_actividad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoo_actividad
    ADD CONSTRAINT fk_szact_actividad FOREIGN KEY (id_actividad_zoocriadero) REFERENCES public.actividad_zoocriadero(id_actividad_zoocriadero);


--
-- TOC entry 5012 (class 2606 OID 41780)
-- Name: seguimiento_zoo_actividad fk_szact_seguimiento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoo_actividad
    ADD CONSTRAINT fk_szact_seguimiento FOREIGN KEY (id_seguimiento_zoo) REFERENCES public.seguimiento_zoocriadero(id_seguimiento_zoo);


--
-- TOC entry 5017 (class 2606 OID 41785)
-- Name: tanque fk_tanque_tipo_tanque; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT fk_tanque_tipo_tanque FOREIGN KEY (id_tipo_tanque) REFERENCES public.tipo_tanque(id_tipo_tanque);


--
-- TOC entry 5018 (class 2606 OID 41790)
-- Name: tanque fk_tanque_zoocriadero; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT fk_tanque_zoocriadero FOREIGN KEY (id_zoocriadero) REFERENCES public.zoocriadero(id_zoocriadero);


--
-- TOC entry 5019 (class 2606 OID 41795)
-- Name: usuario fk_usuario_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- TOC entry 5020 (class 2606 OID 41800)
-- Name: usuario fk_usuario_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fk_usuario_tipo_documento FOREIGN KEY (id_tipo_documento) REFERENCES public.tipo_documento(id_tipo_documento);


--
-- TOC entry 5021 (class 2606 OID 41805)
-- Name: zoocriadero fk_zoocriadero_barrio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT fk_zoocriadero_barrio FOREIGN KEY (id_barrio) REFERENCES public.barrio(id_barrio);


--
-- TOC entry 5022 (class 2606 OID 41810)
-- Name: zoocriadero fk_zoocriadero_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT fk_zoocriadero_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


-- Completed on 2026-09-19 17:15:40

--
-- PostgreSQL database dump complete
--

\unrestrict V3Eu0M2kgdZ2aqhOThFr3zLK6Bd6S3kflvEVKANev15Q9WlFFtONJVjYDcubHQb

