BEGIN;

CREATE TABLE comuna (
    id_comuna   SMALLINT     NOT NULL,
    nombre      VARCHAR(120) NOT NULL,
    CONSTRAINT pk_comuna PRIMARY KEY (id_comuna)
);

CREATE TABLE barrio (
    id_barrio   SMALLINT     NOT NULL,
    nombre      VARCHAR(120) NOT NULL,
    id_comuna   SMALLINT     NOT NULL,
    CONSTRAINT pk_barrio PRIMARY KEY (id_barrio),
    CONSTRAINT fk_barrio_comuna FOREIGN KEY (id_comuna)
        REFERENCES comuna (id_comuna)
);

CREATE TABLE sitio_terreno (
    id_sitio    SMALLINT      NOT NULL,
    direccion   VARCHAR(50),
    CONSTRAINT pk_sitio_terreno PRIMARY KEY (id_sitio)
);

CREATE TABLE sitio_barrio (
    id_sitio_barrio SMALLINT NOT NULL,
    id_sitio        SMALLINT NOT NULL,
    id_barrio       SMALLINT NOT NULL,
    CONSTRAINT pk_sitio_barrio PRIMARY KEY (id_sitio_barrio),
    CONSTRAINT fk_sitio_barrio_sitio FOREIGN KEY (id_sitio)
        REFERENCES sitio_terreno (id_sitio),
    CONSTRAINT fk_sitio_barrio_barrio FOREIGN KEY (id_barrio)
        REFERENCES barrio (id_barrio)
);

CREATE TABLE rol (
    id_rol      SMALLINT    NOT NULL,
    nombre_rol  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_rol PRIMARY KEY (id_rol)
);

CREATE TABLE tipo_documento (
    id_tipo_documento SMALLINT     NOT NULL,
    nombre            VARCHAR(120) NOT NULL,
    CONSTRAINT pk_tipo_documento PRIMARY KEY (id_tipo_documento)
);

CREATE TABLE usuario (
    id_usuario        SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    id_rol            SMALLINT    NOT NULL,
    documento         VARCHAR(50) NOT NULL,
    nombres           VARCHAR(50) NOT NULL,
    apellidos         VARCHAR(50) NOT NULL,
    id_tipo_documento INTEGER     NOT NULL,
    contraseña        VARCHAR(255) NOT NULL,
    correo            VARCHAR(150) NOT NULL UNIQUE,
    fecha_nacimiento  DATE NOT NULL,
    telefono          VARCHAR(20) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_documento UNIQUE (documento),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
        REFERENCES rol (id_rol),
    CONSTRAINT fk_usuario_tipo_documento FOREIGN KEY (id_tipo_documento)
        REFERENCES tipo_documento (id_tipo_documento)
);

CREATE TABLE tipo_deposito (
    id_tipo_deposito SMALLINT    NOT NULL,
    descripcion      VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tipo_deposito PRIMARY KEY (id_tipo_deposito)
);

CREATE TABLE deposito (
    id_deposito      SMALLINT NOT NULL,
    id_sitio         SMALLINT NOT NULL,
    id_tipo_deposito SMALLINT NOT NULL,
    CONSTRAINT pk_deposito PRIMARY KEY (id_deposito),
    CONSTRAINT fk_deposito_sitio FOREIGN KEY (id_sitio)
        REFERENCES sitio_terreno (id_sitio),
    CONSTRAINT fk_deposito_tipo_deposito FOREIGN KEY (id_tipo_deposito)
        REFERENCES tipo_deposito (id_tipo_deposito)
);

CREATE TABLE actividad_terreno (
    id_actividad_terreno SMALLINT     NOT NULL,
    nombre                VARCHAR(120) NOT NULL,
    CONSTRAINT pk_actividad_terreno PRIMARY KEY (id_actividad_terreno)
);

CREATE TABLE seguimiento_terreno (
    id_seguimiento_terreno SMALLINT NOT NULL,
    id_deposito             SMALLINT NOT NULL,
    id_usuario              SMALLINT NOT NULL,
    fecha                    DATE     NOT NULL,
    id_actividad_terreno    SMALLINT NOT NULL,
    ph                       NUMERIC(3,1),
    temperatura              NUMERIC(4,1),
    larvas_aedes             SMALLINT,
    pupas                    SMALLINT,
    larvas_culex             SMALLINT,
    CONSTRAINT pk_seguimiento_terreno PRIMARY KEY (id_seguimiento_terreno),
    CONSTRAINT fk_seguimiento_terreno_deposito FOREIGN KEY (id_deposito)
        REFERENCES deposito (id_deposito),
    CONSTRAINT fk_seguimiento_terreno_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),
    CONSTRAINT fk_seguimiento_terreno_actividad FOREIGN KEY (id_actividad_terreno)
        REFERENCES actividad_terreno (id_actividad_terreno)
);

CREATE TABLE zoocriadero (
    id_zoocriadero SMALLINT    NOT NULL,
    direccion      VARCHAR(50) NOT NULL,
    id_usuario     SMALLINT    NOT NULL,
    id_barrio      SMALLINT    NOT NULL,
    CONSTRAINT pk_zoocriadero PRIMARY KEY (id_zoocriadero),
    CONSTRAINT fk_zoocriadero_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),
    CONSTRAINT fk_zoocriadero_barrio FOREIGN KEY (id_barrio)
        REFERENCES barrio (id_barrio)
);

CREATE TABLE tipo_tanque (
    id_tipo_tanque SMALLINT    NOT NULL,
    descripcion    VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tipo_tanque PRIMARY KEY (id_tipo_tanque)
);

CREATE TABLE tanque (
    id_tanque      SMALLINT    NOT NULL,
    id_zoocriadero SMALLINT    NOT NULL,
    id_tipo_tanque SMALLINT    NOT NULL,
    estado         VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tanque PRIMARY KEY (id_tanque),
    CONSTRAINT fk_tanque_zoocriadero FOREIGN KEY (id_zoocriadero)
        REFERENCES zoocriadero (id_zoocriadero),
    CONSTRAINT fk_tanque_tipo_tanque FOREIGN KEY (id_tipo_tanque)
        REFERENCES tipo_tanque (id_tipo_tanque)
);

CREATE TABLE actividad_zoocriadero (
    id_actividad_zoocriadero SMALLINT     NOT NULL,
    nombre                     VARCHAR(120) NOT NULL,
    CONSTRAINT pk_actividad_zoocriadero PRIMARY KEY (id_actividad_zoocriadero)
);

CREATE TABLE seguimiento_zoocriadero (
    id_seguimiento_zoo       SMALLINT NOT NULL,
    id_tanque                 SMALLINT NOT NULL,
    id_usuario                SMALLINT NOT NULL,
    fecha                      DATE     NOT NULL,
    id_actividad_zoocriadero  SMALLINT NOT NULL,
    ph                         NUMERIC(3,1),
    temperatura                NUMERIC(4,1),
    peces_muertos              SMALLINT,
    peces_nacidos              SMALLINT,
    observaciones              TEXT,
    CONSTRAINT pk_seguimiento_zoocriadero PRIMARY KEY (id_seguimiento_zoo),
    CONSTRAINT fk_seguimiento_zoo_tanque FOREIGN KEY (id_tanque)
        REFERENCES tanque (id_tanque),
    CONSTRAINT fk_seguimiento_zoo_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario),
    CONSTRAINT fk_seguimiento_zoo_actividad FOREIGN KEY (id_actividad_zoocriadero)
        REFERENCES actividad_zoocriadero (id_actividad_zoocriadero)
);


INSERT INTO rol (id_rol, nombre_rol) VALUES
(1, 'Administrador del Sistema'),
(2, 'Coordinador Control Biológico'),
(3, 'Auxiliar Zoocriadero'),
(4, 'Auxiliar Terrero'),
(5, 'Coordinador Ecosalud'),
(6, 'Auxiliar Ecosalud');

INSERT INTO tipo_documento (id_tipo_documento, nombre) VALUES
(1, 'Cédula de ciudadanía');


INSERT INTO usuario
(id_usuario, id_rol, documento, nombres, apellidos, id_tipo_documento, contraseña, correo, fecha_nacimiento, telefono)
VALUES
(1, 1, '0000000000', 'Administrador', 'GEMO', 1,
 '$2y$12$MhZKotIZbUyHdWVgEVz41.P4c/h3SjB5M1kciqxTH9Egbe3gWqNvC',
 'admin@gemo.local', '1990-01-01', '3000000000');

COMMIT;


-- ============================================================
-- Recuperación de contraseña GEMO
-- ============================================================
CREATE TABLE IF NOT EXISTS public.password_reset_codes (
    id_reset integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario smallint NOT NULL,
    codigo_hash character varying(255) NOT NULL,
    expira_en timestamp without time zone NOT NULL,
    intentos smallint NOT NULL DEFAULT 0,
    verificado boolean NOT NULL DEFAULT false,
    usado_en timestamp without time zone,
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_usuario
    ON public.password_reset_codes(id_usuario);

CREATE INDEX IF NOT EXISTS idx_password_reset_expira
    ON public.password_reset_codes(expira_en);

