CREATE TABLE IF NOT EXISTS public.password_reset_codes (
    id_reset integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario smallint NOT NULL,
    codigo_hash character varying(255) NOT NULL,
    expira_en timestamp without time zone NOT NULL,
    intentos smallint NOT NULL DEFAULT 0,
    verificado boolean NOT NULL DEFAULT false,
    usado_en timestamp without time zone,
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_usuario
    ON public.password_reset_codes(id_usuario);

CREATE INDEX IF NOT EXISTS idx_password_reset_expira
    ON public.password_reset_codes(expira_en);
